### ISSUE TITLE
[ToDo] Initialize Project 

### ISSUE THREAD

**Issue by Lights999** [backstreetwx/Pac-Man#2]
- [x] Make these labels  
  https://github.com/Hao-Chen-Fakala/PJRhythmButton/labels  
- [x] Make wiki for Project Regulation  
  https://github.com/backstreetwx/Pac-Man/issues/1  
- [x] Initialize Unity Project [PR](https://github.com/backstreetwx/Pac-Man/pull/4)
  - [x] Make new branch
  - [x] Fix ignore file
  - [x] Create new Unity Project
  - [x] Make PR
- [x] Fix ignore for RAIN AI [PR](https://github.com/backstreetwx/Pac-Man/pull/5)
  - [x] Make new branch
  - [x] Make PR
  - [x] Import RAIN AI
  - [x] Fix ignore file
    - [x] BT Cache folder
    - [x] BT Cache folder.meta
    - [x] RAIN/Editor/RAINProjectState.*

**Comment by Lights999** [comment]
@backstreetwx Do these  preparatory work

**Comment by Lights999** [comment]
@backstreetwx Added & Fixed some details

**Comment by Lights999** [comment]
Finished
